eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
title: "This is a test"
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/SpatialDB
    username: postgres
    password: password
    platform: postgis
    